// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXGDLQYZebYb9Ij4OZjFc3XDVbnn0-2BY',
    appId: '1:1069830120200:web:64d0bdedd6cc05c6a942bd',
    messagingSenderId: '1069830120200',
    projectId: 'relevents-66ec7',
    authDomain: 'relevents-66ec7.firebaseapp.com',
    storageBucket: 'relevents-66ec7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFOs3Qb9kWB_2nDumIzs8MG3EQu4xn_0',
    appId: '1:1069830120200:android:78d2bffeb24037eda942bd',
    messagingSenderId: '1069830120200',
    projectId: 'relevents-66ec7',
    storageBucket: 'relevents-66ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuDnZKEoUIQiXJaWRITv0ZcJWbD-zINY',
    appId: '1:1069830120200:ios:8d864e7017ce986ea942bd',
    messagingSenderId: '1069830120200',
    projectId: 'relevents-66ec7',
    storageBucket: 'relevents-66ec7.appspot.com',
    iosBundleId: 'com.example.relevents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuDnZKEoUIQiXJaWRITv0ZcJWbD-zINY',
    appId: '1:1069830120200:ios:1b39bbcc21dceca9a942bd',
    messagingSenderId: '1069830120200',
    projectId: 'relevents-66ec7',
    storageBucket: 'relevents-66ec7.appspot.com',
    iosBundleId: 'com.example.relevents.RunnerTests',
  );
}
